### ISSUE TITLE
Is this just input a normal color image and segment out the person?

### ISSUE THREAD

**Issue by lucasjinreal** [huuuuusy/Mask-RCNN-Shiny#1]
Does this need a scratch training?

**Comment by huuuuusy** [comment]
> Does this need a scratch training?

The model does not need to be trained again, since I use the weights trained by COCO directly. Mask-RCNN can divide the results into 80 categories according to COCO and I just specified "person" as the only displayed classification result. However, COCO is not designed for person detection so the accuracy is not very high (you can see the demo video: some strange postures in parkour are hard to be detected and the model sets the "person" to gray image incorrectly), thus you can train the Mask-RCNN by other specific person detection datasets if you want a high accuracy in person detection.
